Listen 8090

<VirtualHost *:8090>
    DocumentRoot /app/php-backend/public_html
    DirectoryIndex index.html index.php

    <Directory /app/php-backend/public_html>
        AllowOverride All
        Require all granted
        Options -Indexes +FollowSymLinks
    </Directory>

    ErrorLog /var/log/apache2/kingswell_error.log
    CustomLog /var/log/apache2/kingswell_access.log combined
</VirtualHost>
